# Generated by Django 6.0.4 on 2026-04-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date published')),
                ('flux', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
