# Generated by Django 6.0.4 on 2026-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
