# Generated by Django 6.0.4 on 2026-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0004_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
